:concurrency: 5
:queues:
  - [mailers, 4]
  - [vote_reminder, 2]
  - [reminders, 2]
  - [default, 2]
  - [newsletter, 2]
  - [newsletters_opt_in, 2]
  - [conference_diplomas, 2]
  - [events, 2]
  - [translations, 2]
  - [user_report, 2]
  - [block_user, 2]
  - [metrics, 1]
  - [exports, 1]
  - [cleanups, 1]
  - [participatory_processes, 1]

:scheduler:
  :schedule:
    CalculateAllMetrics:
      cron: '0 0 0 * * *' # Run at midnight
      class: CalculateAllMetricsJob
      queue: metrics
    PreloadOpenData:
      cron: '0 0 1 * * *' # Run at 01:00
      class: PreloadOpenDataJob
      queue: exports
    ExpireDownloadDataFiles:
      cron: '0 0 2 * * *' # Run at 02:00
      class: ExpireDownloadDataFilesJob
      queue: cleanups
    DeleteRegistrationForms:
      cron: '0 0 3 * * *' # Run at 03:00
      class: DeleteRegistrationFormsJob
      queue: cleanups
    GenerateReminders:
      cron: '0 0 8 * * *' # Run at 08:00
      class: GenerateRemindersJob
      queue: reminders
    DigestDailyReminders:
      cron: '0 0 9 * * *' # Run at 09:00
      class: DigestDailyRemindersJob
      queue: reminders
    DigestWeeklyReminders:
      cron: '0 0 10 * * *' # Run at 10:00
      class: DigestWeeklyRemindersJob
      queue: reminders
    ChangeActiveStep:
      cron: '*/15 * * * *' # Run every 15 minutes
      class: ChangeActiveStepJob
      queue: participatory_processes
